# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

   
name: Sync to S3

on:
  push:
    branches:
      - master
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Configure AWS Credential
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }} # Change this to your region of your bucket
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Display the branch name
      run: echo "Current Branch:${{ github.ref }}"
    - name: Output Run Number
      run: echo "${{ github.run_number }}"
    - name: Replace pom file version
      run: sed -i s@0.0.1-SNAPSHOT@${{ github.ref }}-${{ github.run_number }}@g pom.xml
   
    - name: Sync to S3
      run: aws s3 sync . s3://sla54321

